# fly.toml app configuration file generated for chat-with-your-docs-backend-3-spring-bush-7707 on 2023-12-05T02:45:20+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "chat-with-your-docs-backend-3-spring-bush-7707"
primary_region = "bos"

[build]

# Update this env
[env]
  MONGODB_URI = "mongodb+srv://username:password@xxx.xxx.mongodb.net/?retryWrites=true&w=majority"
  OPENAI_API_KEY = "sk-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
